
cp:
	cp 11.lua 22.lua
	cp 11.lua 33.lua
	cp 11.lua 44.lua
	cp 11.lua 55.lua
	cp 11.lua 66.lua
	cp 11.lua 77.lua

run:
	luajit 11.lua &
	luajit 22.lua &
	luajit 33.lua &
	luajit 44.lua &
	luajit 55.lua &
	luajit 66.lua &
	luajit 77.lua &
